
/* Statement :- Print Resume
   Programmar:- Ashutosh Kumar
*/
#include<stdio.h>
#include<conio.h>
void main()
{
 clrscr();
 printf("Name:-Ashutosh Kumar\n");
 printf("S/O :-Shree Sanjay Tiwari\n");
 printf("Addr:-At+Post-Bhagalpur\n\tState-Bihar\n");
 printf("Mob :-8298919231\n");
 printf("Mail:-Kumarashutosh017@gmail.com\n");
 printf("\n");
 printf("Educational Details\n");
 printf("B.tech:-ACEIT,Kukas,Jaipur\n");
 printf("12th  :-L.N.Inter ashtriya high school\n");
 printf("10th  :-Shermari high school\n");
 getch();
}